//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixurf.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PixurfDBContext : DbContext
    {
        public PixurfDBContext()
            : base("name=PixurfDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Relation> User_Relations { get; set; }
    }
}
